################################# Default configuration ###################
# provide your domain here
baseURL = "developers.engineerica.com"
# theme
theme = "dot-theme"
# site title
title = "Engineerica Developer Hub"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "UA-36016803-3"
publishDir = "../docs"

# unsafe html
[markup.goldmark.renderer]
unsafe= true


################################# navigation ################################
[[menu.main]]
name = "About"
url = "about"
weight = 1

[[menu.main]]
name = "Getting Started"
url = "gettingstarted"
weight = 2

[[menu.main]]
name = "Contact Us"
url = "https://www.engineerica.com/contact/"
weight = 3

# Dropdown menu
[[menu.main]]
weight = 4
name = "API Reference"
url = "contactus"
hasChildren = true

  [[menu.main]]
  parent = "API Reference"
  name = "AccuCampus"
  url = "accucampus"
  weight = 1

  [[menu.main]]
  parent = "API Reference"
  name = "AccuClub"
  url = "accuclub"
  weight = 2

  [[menu.main]]
  parent = "API Reference"
  name = "AccuTraining"
  url = "accutraining"
  weight = 3


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#02007e"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/Engineerica/"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/engineerica?lang=en"
  
[[params.social]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "https://www.youtube.com/user/engineerica"
  
[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/engineerica-systems-inc-/"

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
home = "Home"
copyright = "The Hugo Documents are copyright © [gethugothemes](https://gethugothemes.com/) 2020."

# banner
[Languages.en.params.banner]
title = "Engineerica Developer Hub"
subtitle = "Explore the RESTful APIs and resources for our products and services"
bg_image = "images/banner-bg.png" 
placeholder = "Search for a product or page"

# call to action
[Languages.en.params.cta]
enable = true
title = "Stay up to date with Engineerica's Developers"
content = "The latest version of the source code for our API documentation websites can be viewed or downloaded here:"
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "GitHub repository"
link = "https://github.com/engineerica/engineerica-dev"

